apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lazarus
  labels:
    project: lazarus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/lazarus-argocd
    targetRevision: LAZARUS
    path: argo-application/
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true