apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    project: monitoring
  name: alertmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/lazarus-cluster-monitoring
    targetRevision: LAZARUS
    path: argocd-manifest/alertmanager
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true