apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/lazarus-cluster-monitoring
    targetRevision: LAZARUS
    path: manifests/grafana
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true