apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ingress
  labels:
    project: internal-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/lazarus-argocd
    targetRevision: LAZARUS
    path: projects/internal-ingress
    directory:
      recurse: true
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true