---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-there
  namespace: hello-there
spec:
  selector:
    matchLabels:
      name: hello-there
  template:
    metadata:
      labels:
        name: hello-there
    spec:
      containers:
        - name: hello-there
          image: calavelas/hello-there:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-there
  namespace: hello-there
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: hello-there